server:
  port: 7777

spring:
  application:
    name: product-service
# spring cloud alibaba
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        client-ip: 192.168.1.102
        port: 8712
      eager: true
management:
  endpoint:
    sentinel:
      enabled: true
