server:
  port: 8080
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#feign:
#  client:
#    config:
#      connectTimeout: 2000
#      readTimeout: 2000
